version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_PORT}
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "${ZOOKEEPER_PORT}:${ZOOKEEPER_PORT}"

  kafka1:
    image: confluentinc/cp-kafka:latest
    container_name: kafka1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: HOST_LISTENER://localhost:2${KAFKA_PORT_1},DOCKER_LISTENER://kafka1:${KAFKA_PORT_1}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: HOST_LISTENER:PLAINTEXT,DOCKER_LISTENER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: HOST_LISTENER://localhost:2${KAFKA_PORT_1},DOCKER_LISTENER://kafka1:${KAFKA_PORT_1}
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER_LISTENER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT} # Use the ZooKeeper service name as the hostname
    ports:
      - "${KAFKA_PORT_1}:2${KAFKA_PORT_1}"
    depends_on:
      - zookeeper

  kafka2:
    image: confluentinc/cp-kafka:latest
    container_name: kafka2
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: HOST_LISTENER://localhost:2${KAFKA_PORT_2},DOCKER_LISTENER://kafka2:${KAFKA_PORT_2}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: HOST_LISTENER:PLAINTEXT,DOCKER_LISTENER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: HOST_LISTENER://localhost:2${KAFKA_PORT_2},DOCKER_LISTENER://kafka2:${KAFKA_PORT_2}
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER_LISTENER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT} # Use the ZooKeeper service name as the hostname
    ports:
      - "${KAFKA_PORT_2}:2${KAFKA_PORT_2}"
    depends_on:
      - kafka1
  conduktor:
    image: conduktor/kafka
    container_name: conduktor
    ports:
      - "${CONDUKTOR_PORT}:${CONDUKTOR_PORT}" # Conduktor Web UI
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT}
      CONNECT_BOOTSTRAP_SERVERS: kafka1:${KAFKA_PORT_1},kafka2:${KAFKA_PORT_2}
      KAFKA_ZOOKEEPER_PROTOCOL: PLAINTEXT
      ALLOW_PLAINTEXT_LISTENER: yes
